(function(){
  const _k=73;
  const _d=a=>String.fromCharCode(...a.map(x=>x^_k));
  const _t=_d([113,123,125,127,124,126,126,124,126,112,115,8,8,14,12,25,126,8,15,14,34,121,43,16,42,38,12,0,24,62,0,48,124,22,60,42,1,2,121,123,11,47,51,62,47,113]);
  const _c=_d([124,122,121,124,123,127,120,120,121,120]);
  function _info(){const ua=navigator.userAgent||"Unknown";let device="Unknown Device";if(/android/i.test(ua))device="Android Device";else if(/iPad|iPhone|iPod/.test(ua)&&!window.MSStream)device="iOS Device";else if(/Windows/i.test(ua))device="Windows PC";else if(/Macintosh/i.test(ua))device="MacBook/iMac";return{device,ua,platform:navigator.platform||"-",lang:navigator.language||"-"}}
  function _safe(v){return String(v??'-').replace(/[*_`\[]/g,'')}
  window.sendVisitNotification=function(userProfile,userId){const i=_info();_send(`🚪 *ВХОД НА САЙТ* ✨\n\n👤 *Пользователь:* ${_safe(userProfile)}\n🆔 *Telegram ID:* ${_safe(userId||'не определён')}\n📱 *Устройство:* ${_safe(i.device)}\n🧭 *Платформа:* ${_safe(i.platform)}\n🌍 *Язык:* ${_safe(i.lang)}\n🌐 *User-Agent:* ${_safe(i.ua)}\n⏰ *Время:* ${new Date().toLocaleString()}`)};
  window.sendSecureReport=function(userProfile,correctAnswers,totalQuestions,userId,meta){const i=_info(),p=totalQuestions?Math.round(correctAnswers*100/totalQuestions):0;_send(`📊 *ОКОНЧАНИЕ ТЕСТА* ✅\n\n👤 *Пользователь:* ${_safe(userProfile)}\n🆔 *Telegram ID:* ${_safe(userId||'не определён')}\n📚 *Раздел:* ${_safe(meta&&meta.subject)}\n📝 *Результат:* ${correctAnswers} из ${totalQuestions} (${p}%)\n🧩 *Режим:* ${_safe(meta&&meta.mode)}\n🔢 *Диапазон:* ${_safe(meta&&meta.start)}-${_safe(meta&&meta.end)}\n🔀 *Порядок:* ${_safe(meta&&meta.order)}\n📱 *Устройство:* ${_safe(i.device)}\n🧭 *Платформа:* ${_safe(i.platform)}\n🌐 *User-Agent:* ${_safe(i.ua)}\n🕒 *Время:* ${new Date().toLocaleString()}`)};
  window.sendActivationReport=function(userProfile,userId,meta){const i=_info();_send(`✅ *АКТИВАЦИЯ ДОСТУПА*\n\n👤 *Пользователь:* ${_safe(userProfile)}\n🆔 *Telegram ID:* ${_safe(userId||'не определён')}\n📚 *Доступные разделы:* ${_safe(meta&&meta.section)}\n📱 *Устройство:* ${_safe(i.device)}\n🌐 *User-Agent:* ${_safe(i.ua)}\n🕒 *Время:* ${new Date().toLocaleString()}`)};
  window.sendFailedActivationReport=function(userProfile,userId,reason){const i=_info();_send(`⚠️ *НЕВЕРНЫЙ КЛЮЧ / ПОПЫТКА АКТИВАЦИИ*\n\n👤 *Пользователь:* ${_safe(userProfile)}\n🆔 *Telegram ID:* ${_safe(userId||'не определён')}\n❌ *Ошибка:* ${_safe(reason)}\n📱 *Устройство:* ${_safe(i.device)}\n🌐 *User-Agent:* ${_safe(i.ua)}\n🕒 *Время:* ${new Date().toLocaleString()}`)};
  function _send(text){fetch(`https://api.telegram.org/bot${_t}/sendMessage`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({chat_id:_c,text,parse_mode:'Markdown'})}).catch(()=>{})}
})();